# Generated by Django 6.0.1 on 2026-01-16 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Takım Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Logo')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Kuruluş Tarihi')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir')),
                ('stadium', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadyum')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('player', 'Oyuncu'), ('coach', 'Antrenör'), ('assistant_coach', 'Yardımcı Antrenör'), ('manager', 'Yönetici'), ('staff', 'Personel')], default='player', max_length=20, verbose_name='Üye Tipi')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pozisyon')),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Forma Numarası')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='Katılma Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='team.team', verbose_name='Takım')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Takım Üyesi',
                'verbose_name_plural': 'Takım Üyeleri',
                'ordering': ['team', 'user__adi', 'user__soyadi'],
            },
        ),
    ]
