# Generated by Django 6.0.1 on 2026-01-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='team',
            name='website',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='jersey_number',
        ),
    ]
