# Generated by Django 6.0.1 on 2026-01-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_team_city_remove_team_stadium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='member_type',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='position',
        ),
        migrations.AddField(
            model_name='teammember',
            name='adi',
            field=models.CharField(blank=True, max_length=30, verbose_name='Adı'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='okulu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Okulu'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='soyadi',
            field=models.CharField(blank=True, max_length=30, verbose_name='Soyadı'),
        ),
    ]
