# Generated by Django 6.0.1 on 2026-01-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_teammember_member_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_members/', verbose_name='Fotoğraf'),
        ),
    ]
