# Generated by Django 6.0.1 on 2026-01-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_teammember_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='dogum_tarihi',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='adi',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='okulu',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='soyadi',
            new_name='surname',
        ),
    ]
