# Generated by Django 6.0.1 on 2026-01-17 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_rename_dogum_tarihi_teammember_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Ay')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='team.teammember', verbose_name='Üye')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-month', 'member'],
                'unique_together': {('member', 'month')},
            },
        ),
    ]
