# Generated by Django 6.0.1 on 2026-01-21 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(verbose_name='Gün')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('location', models.CharField(choices=[('TOBB', 'TOBB'), ('AYTEN SABAN', 'AYTEN SABAN')], max_length=200, verbose_name='Lokasyon')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='team.team', verbose_name='Takım')),
            ],
            options={
                'verbose_name': 'Antrenman',
                'verbose_name_plural': 'Antrenmanlar',
                'ordering': ['-day_of_week', 'time'],
            },
        ),
    ]
