# Generated by Django 6.0.1 on 2026-01-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_teammember_user_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Bitiş Saati'),
        ),
        migrations.AddField(
            model_name='training',
            name='trainer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Antrenör'),
        ),
        migrations.AlterField(
            model_name='training',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')], verbose_name='Gün'),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(choices=[('TOBB', 'TOBB'), ('AYTEN SABAN', 'AYTEN SABAN'), ('Diğer', 'Diğer')], max_length=200, verbose_name='Lokasyon'),
        ),
    ]
