# Generated by Django 6.0.1 on 2026-01-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_alter_training_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Antrenör'),
        ),
    ]
