# Generated by Django 6.0.2 on 2026-02-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='member',
        ),
    ]
