# Generated by Django 6.0.2 on 2026-02-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_remove_questionnaire_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='team.team', verbose_name='Takım'),
        ),
    ]
