# Generated by Django 6.0.2 on 2026-02-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_questionnaire_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
    ]
