# Generated by Django 6.0.2 on 2026-02-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_questionnaire_begin_date_questionnaire_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='team',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='questionnaires', to='team.team', verbose_name='Takımlar'),
        ),
    ]
