# Generated by Django 6.0.4 on 2026-04-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_remove_questionnaire_team_questionnaire_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='questionnaires', to='team.team', verbose_name='Takımlar'),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(choices=[('TOBB', 'TOBB'), ('AYTEN SABAN', 'AYTEN SABAN'), ('SPORTIF YASAM', 'SPORTIF YASAM'), ('FENERBAHCE', 'FENERBAHCE'), ('Diğer', 'Diğer')], max_length=200, verbose_name='Lokasyon'),
        ),
    ]
