# Generated by Django 6.0.1 on 2026-01-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
